### ISSUE TITLE
ModuleNotFoundError: No module named 'pytorch_lightning.metrics.functional.classification'

### ISSUE THREAD

**Issue by LiuCMU** [gmum/huggingmolecules#13]
Hi, when executing `quick_tour.py`, it throws me the following error in line 9:
```
Traceback (most recent call last):
  File "quick_tour.py", line 9, in <module>
    from experiments.src import TrainingModule, get_data_loaders
  File "/home/jack/huggingmolecules/experiments/src/__init__.py", line 1, in <module>
    from experiments.src.training.training_lightning_module import TrainingModule
  File "/home/jack/huggingmolecules/experiments/src/training/__init__.py", line 1, in <module>
    from .training_train_model import train_model
  File "/home/jack/huggingmolecules/experiments/src/training/training_train_model.py", line 6, in <module>
    from .training_lightning_module import TrainingModule
  File "/home/jack/huggingmolecules/experiments/src/training/training_lightning_module.py", line 8, in <module>
    from experiments.src.training.training_metrics import BatchWeightedLoss
  File "/home/jack/huggingmolecules/experiments/src/training/training_metrics.py", line 7, in <module>
    from pytorch_lightning.metrics.functional.classification import auroc
ModuleNotFoundError: No module named 'pytorch_lightning.metrics.functional.classification'
```

I tried at my local desktop and a remote server, but both gave the same error. Attached is my environment yaml file. Do you have any thoughts about the issue? Thank you!
[huggingmolecules.txt](https://github.com/gmum/huggingmolecules/files/6957138/huggingmolecules.txt)

**Comment by panpiort8** [comment]
Hi :)  quick-tour uses `experiments` module which has some additional dependencies (see https://github.com/gmum/huggingmolecules#the-experiments-module). You have pytorch-lightning==1.4.1 installed, while pytorch-lightning==1.0.6 is required (see [requirements.txt](https://github.com/gmum/huggingmolecules/blob/main/experiments/requirements.txt)). Unfortunately, pytorch-lightning is not backward compatible (at least to my knowledge). Try to reinstall pytorch-lightning with a proper version or just run `pip install -r experiments/requirements.txt`.

**Comment by LiuCMU** [comment]
Thank you very much for the comment! I solved the issue by replacing `from pytorch_lightning.metrics.functional.classification import auroc` as` from sklearn.metrics import roc_auc_score as auroc`, since it's just an evaluation metric :)

**Comment by panpiort8** [comment]
Great! Thanks for using huggingmolecules! If you have any other issue or comment - feel free to contact us :)
