### ISSUE TITLE
no setup.py

### ISSUE THREAD

**Issue by ioneliabuzatu** [gmum/huggingmolecules#26]
What's the reason for not installing it from python with pip yet?

Update: oh i see setup.py is in src/ - if you move the setup.py in the root folder then people can do pip install git+[git_repo_url](https://github.com/gmum/huggingmolecules)

**Comment by ioneliabuzatu** [comment]
useful link how to do it: https://stackoverflow.com/questions/14417236/setup-py-renaming-src-package-to-project-name
also: https://medium.com/analytics-vidhya/explicit-understanding-of-python-package-building-structuring-4ac7054c0749

**Comment by panpiort8** [comment]
Hi! Thanks for your suggestion. The main reason why our package cannot be installed with pip (pip install huggingmolecules) is that we have dependency on rdkit package. Installing rdkit with pip is difficult for some [reasons](http://rdkit.blogspot.com/2019/11/why-rdkit-isnt-available-on-pypi.html) and we don't have time for struggling with them. Then, even if an user has an option to directly install huggingmolecules with pip, he is to install rdkit with conda anyway. We believe it is less confusing for the user if he installs the package by following the instruction from README.md.
