### ISSUE TITLE
Loading fine-tuned model checkpoint (last.ckpt) for prediction

### ISSUE THREAD

**Issue by sbadirli** [gmum/huggingmolecules#27]
Hi,

Thanks for providing code for multiple projects. I am having a trouble to load the fine-tuned model checkpoint to make a prediction. I used 2 different ways to do that in both times I got an error. Any help is appreciated.

```
trainer = Trainer()
path_ckpt = 'experiments_results/Tune_MatModel_ADME_freesolv/trial_1/Tune_MatModel_ADME_freesolv/last.ckpt'

checkpoint = torch.load(path_ckpt, map_location=torch.device('cpu'))
pl_model = TrainingModule.load_state_dict(checkpoint['state_dict'])

# Version 1:
results = trainer.test(ckpt_path=path_ckpt, test_dataloaders=test_loader)
print(results)

#Version 2
trainer2 = Trainer()
results2 = trainer2.test(model=pl_model, test_dataloaders=test_loader)
```

__TrainingModule__ is my PyTorch-lightning model.  The error I am getting for __pl_model = TrainingModule.load_state_dict(checkpoint['state_dict'])__ is as below:

```
File "<stdin>", line 1, in <module>
TypeError: load_state_dict() missing 1 required positional argument: 'state_dict'
```
 And for __results = trainer.test(ckpt_path=path_ckpt, test_dataloaders=test_loader)__  is as below:
```
model.load_state_dict(ckpt['state_dict'])
AttributeError: 'NoneType' object has no attribute 'load_state_dict'
```
I did some search on these errors and it seems the errors appear due to hyper parameters not being saved explicitly. Is that right? 

Best,
Sarkhan

**Comment by panpiort8** [comment]
Hello :) sorry for the delay. Could you please provide the entire script? I'm not really sure what's going on. Is `TrainingModule` a class or an instance? If it's instance, then `load_state_dict` method changes the object and returns None (that may be the reason for your second error).
