### ISSUE TITLE
RMAT with and without RDKit has the same .pt file?

### ISSUE THREAD

**Issue by pjspol** [gmum/huggingmolecules#37]
In models_rmat.py, the .pt file is the same for both RMAT with and without RDKit. Is that supposed to be the case?
<img width="1274" alt="Screen Shot 2022-10-01 at 10 38 00 PM" src="https://user-images.githubusercontent.com/86651673/193435452-4a0be75a-5663-40d1-b0e4-8c3b3f765eb9.png">

**Comment by panpiort8** [comment]
Thanks for your concern! It is supposed to be like that because the rdkit features are added just before the classifier head which is excluded from the pre-trained weights.
